# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
# Copy both project files before restore (the host references Core) so layer caching works.
COPY src/LupiraContactApi/LupiraContactApi.csproj src/LupiraContactApi/
COPY src/LupiraContactApi.Core/LupiraContactApi.Core.csproj src/LupiraContactApi.Core/
RUN dotnet restore src/LupiraContactApi/LupiraContactApi.csproj
COPY . .
# The openapi document is a repo artifact, regenerated by a normal build — not by the image build.
RUN dotnet publish src/LupiraContactApi/LupiraContactApi.csproj -c Release -o /app --no-restore /p:OpenApiGenerateDocumentsOnBuild=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
# curl: compose healthcheck (curl -fsS .../readyz).
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
COPY --from=build /app .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "LupiraContactApi.dll"]
